env:
    MANIFEST: https://github.com/BootleggersROM/manifest.git -b tirimbino
    DEVICE: lavender
    OEM: xiaomi
    DT_LINK: https://github.com/miteshx07/dt13.git -b 13.0
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/miteshx07/vt13.git -b 13.0
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/miteshx07/kernel_xiaomi_lavender.git -b a13-qti-camfix
    RS_LINK: https://github.com/miteshx07/android_packages_resources_devicesettings.git -b lineage-20.0
    RS_PATH: packages/resources/devicesettings
    VA_LINK: https://github.com/miteshx07/packages_apps_ViPER4AndroidFX.git -b main
    VA_PATH: packages/apps/ViPER4AndroidFX
    PLATFORM: sdm660
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: bootleg_${DEVICE}-userdebug
    OUTPUT: BootleggersROM*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - git clone $RS_LINK $RS_PATH
      - git clone $VA_LINK $VA_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - source build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

